#!/bin/sh -e
                                                                                
case "$1" in
abort-install | remove | abort-upgrade | upgrade | failed-upgrade | disappear)
        ;;
purge)
        cd /etc/ssl/certs
        PATH=$PATH:/usr/bin/ssl
        rm -f `openssl x509 -noout -hash < stone.pem`.0
        rm -f stone.pem
        ;;
*)
        echo "$0: incorrect arguments: $*" >&2
        exit 1
        ;;
esac

#DEBHELPER#
